name: test
on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]
jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '19'
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: testCodeCoverageReport --info --no-daemon --stacktrace --warning-mode all
      - name: Upload coverage to Codecov
        if: github.base_ref != null
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
