name: test
on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]
jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '19'
      - name: Setup JavaAgent for guard pattern
        run: |
          # In case the file does not have a newline at the end
          echo '' >> gradle.properties
          echo "org.gradle.jvmargs = -javaagent:${{ github.workspace }}/gradle/guard-pattern-fix.jar" >> gradle.properties
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: testCodeCoverageReport --no-daemon --stacktrace --warning-mode all
      - name: Test report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: junit-tests
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Upload coverage to Codecov
        if: github.base_ref != null
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
