name: nightly
on:
  push:
    branches: [main, ci]
jobs:
  move-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Move ci tag
        run: |
          mkdir repo
          git clone -b "$BRANCH_NAME" "https://github.com/${GITHUB_REPOSITORY}" repo
          cd repo
          bash .github/workflows/move-tag.sh "nightly-build" "Last commit build by the CI"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

  check-aya-version:
    runs-on: ubuntu-latest
    outputs:
      isSnapshot: ${{ steps.check.outputs.isSnapshot }}
    steps:
      - uses: actions/checkout@v2
      - name: Check snapshot version
        id: check
        run: |
          ver="$(cat ./gradle/deps.properties | grep "version.project" | cut -d'=' -f2)"
          isSnapshot="$(echo "$ver" | grep -q "SNAPSHOT" && echo true || echo false)"
          echo "Detected Project Version: $ver"
          echo "Detected Project Version is a SNAPSHOT: $isSnapshot"
          echo "::set-output name=isSnapshot::${isSnapshot}"

  publish-snapshot:
    needs: [check-aya-version]
    runs-on: ubuntu-latest
    if: github.repository == 'aya-prover/aya-dev' && needs.check-aya-version.outputs.isSnapshot == 'true'
    env:
      ossrhUsername: ${{ secrets.OSSRHUSERNAME }}
      ossrhPassword: ${{ secrets.OSSRHPASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '19'
      - name: Setup JavaAgent for guard pattern
        run: |
          # In case the file does not have a newline at the end
          echo '' >> gradle.properties
          echo "org.gradle.jvmargs = -javaagent:${{ github.workspace }}/gradle/guard-pattern-fix.jar" >> gradle.properties
      - name: gradle publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish --info --no-daemon --stacktrace --warning-mode all

  nightly-build:
    needs: [move-tag]
    runs-on: ${{ matrix.os }}
    env:
      jlinkName: aya-prover-jlink-${{ matrix.os }}_${{ matrix.arch }}.zip
      nativeName: aya-native-${{ matrix.os }}_${{ matrix.arch }}${{ matrix.binaryExt }}
      jlinkSha256: aya-prover-jlink-${{ matrix.os }}_${{ matrix.arch }}.sha256.txt
      nativeSha256: aya-native-${{ matrix.os }}_${{ matrix.arch }}.sha256.txt
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86-64
            binaryExt: ''
          - os: macos-latest
            arch: x86-64
            binaryExt: ''
          - os: windows-latest
            arch: x86-64
            binaryExt: '.exe'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '19'

      - name: Setup JavaAgent for guard pattern
        shell: bash
        run: |
          # In case the file does not have a newline at the end
          echo '' >> gradle.properties
          norm="${{ github.workspace }}"
          norm="${norm//\\//}"
          echo "org.gradle.jvmargs = -javaagent:$norm/gradle/guard-pattern-fix.jar" >> gradle.properties

      - name: Run task jlink
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jlink --info --no-daemon --stacktrace --warning-mode all

      - name: Run task fatJar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: fatJar --no-daemon --stacktrace --warning-mode all

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          set-java-home: 'false'
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os }} == 'windows-latest'

      - name: Tell gradle where's my JDK
        run: |
          # Gradle should respect these environmental variables by default!
          echo 'org.gradle.java.installations.fromEnv=JAVA_HOME,GRAALVM_HOME' >> gradle.properties

      - name: Gradle, do you understand?
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javaToolchains --info --no-daemon --stacktrace --warning-mode all

      - name: Run task nativeCompile
        uses: gradle/gradle-build-action@v2
        with:
          arguments: nativeCompile --info --no-daemon --stacktrace --warning-mode all

      - name: Copy aya Native Image
        run: cp ./cli-console/build/native/nativeCompile/aya${{ matrix.binaryExt }} ./${{ env.nativeName }}

      - name: Checksum (Native, Unix)
        run: shasum -a 256 ./${{ env.nativeName }} > ./${{ env.nativeSha256 }}
        if: matrix.os != 'windows-latest'

      - name: Checksum (Native, Windows)
        run: Get-FileHash ./${{ env.nativeName }} -Algorithm SHA256 > ./${{ env.nativeSha256 }}
        if: matrix.os == 'windows-latest'

      - name: Test native image
        run: ./${{ env.nativeName }} --remake base/src/test/resources/success

      - name: Copy fat jar
        run: |
          cp ./ide-lsp/build/libs/lsp-*-fat.jar ./lsp-fatjar.jar
          cp ./cli-console/build/libs/cli-*-fat.jar ./cli-fatjar.jar

      - name: Zip Artifacts (Windows)
        uses: papeloto/action-zip@v1
        with:
          files: ./ide-lsp/build/image
          dest: ${{ env.jlinkName }}
        if: matrix.os == 'windows-latest'

      - name: Checksum (Windows)
        run: |
          Get-FileHash ${{ env.jlinkName }} -Algorithm SHA256 > ${{ env.jlinkSha256 }}
        if: matrix.os == 'windows-latest'

      - name: Zip Artifacts (Unix)
        run: |
          root="$(pwd)"
          cd ./ide-lsp/build/image
          zip -r "$root/${{ env.jlinkName }}" .
          shasum -a 256 "$root/${{ env.jlinkName }}" > "$root/${{ env.jlinkSha256 }}"
        if: matrix.os != 'windows-latest'

      - name: Update Release
        uses: Xotl/cool-github-releases@v1
        with:
          mode: update
          isPrerelease: false
          tag_name: nightly-build
          release_name: "Nightly builds"
          body_mrkdwn: |
            _These are latest builds, but the date on GitHub is frozen due to stupid limitations.
            Corresponding commit: <https://github.com/aya-prover/aya-dev/commit/${{ github.sha }}>_
          assets: ${{ env.jlinkName }};${{ env.jlinkSha256 }};lsp-fatjar.jar;cli-fatjar.jar;${{ env.nativeSha256 }};${{ env.nativeName }}|application/octet-stream
          replace_assets: true
          github_token: ${{ secrets.GH_TOKEN }}
