name : nightly
on :
  push :
    branches : [ main ]
jobs :
  move-tag :
    runs-on : ubuntu-latest
    steps :
      - name : Move ci tag
        uses : s3krit/walking-tag-action@master
        with :
          TAG_NAME : nightly-build
          TAG_MESSAGE : |
            Last commit build by the CI
        env :
          GITHUB_TOKEN : ${{ secrets.GH_TOKEN }}
        if : github.ref == 'refs/heads/main'

  nightly-build :
    needs : [ move-tag ]
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast : false
      matrix :
        os : [ macos-latest, ubuntu-latest, windows-latest ]
    steps :
      - uses : actions/checkout@v2
      - uses : actions/setup-java@v1
        with :
          java-version : '17'
      - uses : eskatos/gradle-command-action@v1
        with :
          dependencies-cache-enabled : true
          arguments : jlink --info --no-daemon --stacktrace --warning-mode all
      - uses : eskatos/gradle-command-action@v1
        with :
          dependencies-cache-enabled : true
          arguments : fatjar --info --no-daemon --stacktrace --warning-mode all
      - run : cp -a ./lsp/build/libs/lsp-*-fat.jar ./lsp-fatjar.jar
      - run : cp -a ./cli/build/libs/lsp-*-fat.jar ./cli-fatjar.jar
      - name : Zip Artifacts
        uses : papeloto/action-zip@v1
        with :
          files : ./lsp/build/image
          dest : aya-prover-jlink-${{ matrix.os }}_x86_64.zip
        if : github.ref == 'refs/heads/main'
      - name : Update the CI tag
        uses : Xotl/cool-github-releases@v1
        with :
          mode : update
          isPrerelease : false
          tag_name : nightly-build
          release_name : "Nightly builds"
          body_mrkdwn : |
            _This is the newest build, but GitHub date can't be updated. Corresponding commit: ${{ github.sha }}_
          assets : aya-prover-jlink-${{ matrix.os }}_x86_64.zip;./lsp-fatjar.jar;./cli-fatjar.jar
          replace_assets : true
          github_token : ${{ secrets.GH_TOKEN }}
        if : github.ref == 'refs/heads/main'

